name: "Setup env"
description: "setup environment"

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  go-version:
    description: "go version"
    required: true
 

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/adm64,linux/arm64/v8
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}
    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - name: Install container-tag-exists
      shell: bash
      run: go install github.com/Hsn723/container-tag-exists@latest  
