name: main
on:
  pull_request:
  push:
    branches:
      - "main"
env:
  go-version: "1.19"
jobs:
  container_build_and_push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go-version: ${{ env.go-version }}
      - name: Build golang-1.19-jammy
        uses: ./.github/actions/build_push
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dir: './golang-all/golang-1.19-focal'
          container-image: "golang"
      - name: Build golang-1.19-focal
        uses: ./.github/actions/build_push
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dir: './golang-all/golang-1.20-focal'
          container-image: "golang"
