name: main
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build_container:
    strategy:
      matrix:
        job:
          - dir: ./golang-all/golang-1.19-focal
            container-image: "golang" 
            platform: "linux/amd64,linux/arm64"
          - dir: ./golang-all/golang-1.19-jammy
            container-image: "golang" 
            platform: "linux/amd64,linux/arm64"

    runs-on: ubuntu-22.04
    env:
      go-version: "1.19"
    steps:
      - uses: actions/checkout@v3
      - name: Setup build environment
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GHCR_TOKEN }}
          go-version: ${{ env.go-version }}
      - name: Build container image
        uses: ./.github/actions/build_push
        with:
          github_token: ${{ secrets.GHCR_TOKEN }}
          dir: ${{ matrix.job.dir }}
          container-image: ${{ matrix.job.container-image }}
          platform:  ${{ matrix.job.platform }}
